[package]
name = "tsz"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
serde = { version = "1.0.152", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0.91", default-features = false, features = ["alloc"] }
bitvec = { version = "1.0.1", default-features = false, features = ["alloc", "atomic"] }

[dev-dependencies]
criterion = "0.4.0"
rand = "0.8.5"

[[bench]]
name = "compression"
harness = false